# Generated by Django 4.2.29 on 2026-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('confirmed', 'নিশ্চিত'), ('cancelled', 'বাতিল'), ('completed', 'সম্পন্ন')], default='pending', max_length=20)),
                ('chamber', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_note', models.TextField(blank=True, help_text='ডাক্তারের নোট (রোগী দেখবে না)')),
            ],
            options={
                'verbose_name': 'অ্যাপয়েন্টমেন্ট',
                'ordering': ['-created_at'],
            },
        ),
    ]
