# Generated by Django 4.2.29 on 2026-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'পরিচিতির হাইলাইট',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'সময় স্লট',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-baby', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField()),
                ('full_content', models.TextField(blank=True)),
                ('is_large', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ব্লগ পোস্ট',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=10)),
                ('icon_class', models.CharField(default='fas fa-scroll', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link_text', models.CharField(default='সনদ যাচাই করুন', max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('is_amber', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'সনদপত্র',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='প্রধান চেম্বার', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('schedule', models.CharField(max_length=300)),
                ('closed_days', models.CharField(default='শুক্রবার: বন্ধ', max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('phone_raw', models.CharField(default='+8801811223344', max_length=20)),
                ('icon_class', models.CharField(default='fas fa-hospital-alt', max_length=100)),
                ('is_amber', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'চেম্বার',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'যোগাযোগ বার্তা',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-check-circle', max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ফি তথ্য',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('fee', models.IntegerField()),
                ('includes', models.CharField(max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ফি তালিকা',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-newspaper', max_length=100)),
                ('outlet_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('is_amber', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'মিডিয়া কভারেজ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', max_length=100)),
                ('entry_type', models.CharField(choices=[('degree', 'স্নাতক ডিগ্রি'), ('postgrad', 'পোস্ট-গ্র্যাজুয়েট'), ('international', 'আন্তর্জাতিক'), ('training', 'বিদেশী প্রশিক্ষণ'), ('current', 'বর্তমান পদ')], default='degree', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'শিক্ষাগত যোগ্যতা',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RatingBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
            options={
                'ordering': ['-stars'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('avatar_letter', models.CharField(blank=True, max_length=5)),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.TextField()),
                ('is_verified', models.BooleanField(default=True)),
                ('is_accent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'রিভিউ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-stethoscope', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'সেবা',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='ডাঃ সানজিদা ইসলাম চৌধুরী', max_length=200)),
                ('doctor_name_en', models.CharField(default='Dr. Sanjida Islam Chowdhury', max_length=200)),
                ('specialty', models.CharField(default='গাইনী ও প্রসূতি বিশেষজ্ঞ', max_length=200)),
                ('degrees', models.CharField(default='MBBS · FCPS · MRCOG (UK)', max_length=300)),
                ('bio', models.TextField(default='')),
                ('phone', models.CharField(default='০১৮১১-২২৩৩৪৪', max_length=20)),
                ('phone_raw', models.CharField(default='+8801811223344', max_length=20)),
                ('whatsapp', models.CharField(default='+8801811223344', max_length=20)),
                ('email', models.EmailField(default='dr.sanjida@example.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/dr.sanjida.bd')),
                ('youtube_url', models.URLField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor/')),
                ('profile_photo_url', models.URLField(blank=True, default='https://cdn.sasthyaseba.com/doctors/7410/xoWEh5iyzT9wpngIPNnKbQQiN5AnbUCE8y2hJYpv/dr-sanjida-hossain.jpg')),
                ('years_experience', models.IntegerField(default=22)),
                ('successful_deliveries', models.IntegerField(default=8000)),
                ('google_rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('google_review_count', models.IntegerField(default=650)),
                ('research_papers', models.IntegerField(default=18)),
                ('booking_fee', models.IntegerField(default=300)),
                ('bkash_number', models.CharField(default='০১৮১১-২২৩৩৪৪', max_length=20)),
                ('nagad_number', models.CharField(default='০১৮১১-২২৩৩৪৪', max_length=20)),
                ('rocket_number', models.CharField(default='০১৮১১২২৩৩৪৪৭', max_length=25)),
                ('map_embed_url', models.TextField(blank=True, default='')),
                ('maps_link', models.URLField(blank=True, default='https://maps.google.com/?q=মিরপুর+ঢাকা')),
                ('meta_title', models.CharField(default='ডাঃ সানজিদা ইসলাম চৌধুরী | গাইনী ও প্রসূতি বিশেষজ্ঞ', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'সাইট সেটিংস',
                'verbose_name_plural': 'সাইট সেটিংস',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('photo_url', models.URLField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-user-md', max_length=100)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'টিম সদস্য',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TickerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'টিকার বার্তা',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-award', max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ভিডিও',
                'ordering': ['order'],
            },
        ),
    ]
