# Generated by Django 6.0.3 on 2026-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='ছবির শিরোনাম (ঐচ্ছিক)', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='আপলোড করুন ছবি', null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='অথবা বাহ্যিক ছবির লিংক দিন')),
                ('order', models.IntegerField(default=0, help_text='ক্রম')),
                ('is_active', models.BooleanField(default=True, help_text='সক্রিয়')),
            ],
            options={
                'verbose_name': 'গ্যালারির ছবি',
                'verbose_name_plural': 'গ্যালারির ছবি',
                'ordering': ['order'],
            },
        ),
    ]
