# Generated by Django 6.0.3 on 2026-03-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='bio',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detailed_bio',
            field=models.TextField(default='', verbose_name='বিস্তারিত পরিচয়'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_bio',
            field=models.TextField(default='', verbose_name='সংক্ষিপ্ত পরিচয়'),
        ),
    ]
