# Generated by Django 6.0.3 on 2026-03-13 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitesettings_bio_sitesettings_detailed_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='রোগীর নাম')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='মোবাইল নম্বর')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='বয়স')),
                ('gender', models.CharField(choices=[('male', 'পুরুষ'), ('female', 'মহিলা'), ('other', 'অন্যান্য')], default='female', max_length=10, verbose_name='লিঙ্গ')),
                ('district', models.CharField(choices=[('tangail', 'টাঙ্গাইল'), ('dhaka', 'ঢাকা'), ('gazipur', 'গাজীপুর'), ('narayanganj', 'নারায়ণগঞ্জ'), ('manikganj', 'মানিকগঞ্জ'), ('munshiganj', 'মুন্সিগঞ্জ'), ('narsingdi', 'নরসিংদী'), ('mymensingh', 'ময়মনসিংহ'), ('jamalpur', 'জামালপুর'), ('kishorganj', 'কিশোরগঞ্জ'), ('other', 'অন্যান্য')], default='tangail', max_length=30, verbose_name='জেলা')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='এলাকা')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('first_visit_date', models.DateField(default=django.utils.timezone.now, verbose_name='প্রথম ভিজিটের তারিখ')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'চেম্বার রোগী',
                'verbose_name_plural': 'চেম্বার রোগী',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChamberVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, verbose_name='ভিজিটের তারিখ')),
                ('visit_type', models.CharField(choices=[('new', 'নতুন রোগী'), ('followup', 'ফলো-আপ')], default='new', max_length=10, verbose_name='ভিজিটের ধরন')),
                ('symptoms', models.TextField(blank=True, verbose_name='লক্ষণ')),
                ('diagnosis', models.TextField(blank=True, verbose_name='রোগ নির্ণয়')),
                ('followup_date', models.DateField(blank=True, null=True, verbose_name='পরবর্তী ফলো-আপ তারিখ')),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ডাক্তার ফি')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.chamberpatient', verbose_name='রোগী')),
            ],
            options={
                'verbose_name': 'ভিজিট',
                'verbose_name_plural': 'ভিজিটসমূহ',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChamberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='পরামর্শ ফি')),
                ('additional_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='অতিরিক্ত চার্জ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='মোট পরিমাণ')),
                ('payment_method', models.CharField(choices=[('cash', 'নগদ'), ('bkash', 'বিকাশ'), ('nagad', 'নগদ (মোবাইল)'), ('card', 'কার্ড')], default='cash', max_length=10, verbose_name='পেমেন্ট পদ্ধতি')),
                ('payment_status', models.CharField(choices=[('paid', 'পরিশোধিত'), ('due', 'বাকি'), ('partial', 'আংশিক')], default='paid', max_length=10, verbose_name='পেমেন্ট অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.chambervisit', verbose_name='ভিজিট')),
            ],
            options={
                'verbose_name': 'পেমেন্ট',
                'verbose_name_plural': 'পেমেন্টসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
