# Generated by Django 6.0.3 on 2026-03-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chamberpatient_chambervisit_chamberpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='এলাকার নাম')),
                ('district', models.CharField(choices=[('tangail', 'টাঙ্গাইল'), ('dhaka', 'ঢাকা'), ('gazipur', 'গাজীপুর'), ('narayanganj', 'নারায়ণগঞ্জ'), ('manikganj', 'মানিকগঞ্জ'), ('munshiganj', 'মুন্সিগঞ্জ'), ('narsingdi', 'নরসিংদী'), ('mymensingh', 'ময়মনসিংহ'), ('jamalpur', 'জামালপুর'), ('kishorganj', 'কিশোরগঞ্জ'), ('other', 'অন্যান্য')], max_length=30, verbose_name='জেলা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'এলাকা',
                'verbose_name_plural': 'এলাকা',
                'ordering': ['district', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AlterField(
            model_name='chamberpatient',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area', verbose_name='এলাকা'),
        ),
    ]
