# Generated by Django 6.0.3 on 2026-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_area_alter_chamberpatient_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberpatient',
            name='district',
            field=models.CharField(blank=True, choices=[('tangail', 'টাঙ্গাইল'), ('dhaka', 'ঢাকা'), ('gazipur', 'গাজীপুর'), ('narayanganj', 'নারায়ণগঞ্জ'), ('manikganj', 'মানিকগঞ্জ'), ('munshiganj', 'মুন্সিগঞ্জ'), ('narsingdi', 'নরসিংদী'), ('mymensingh', 'ময়মনসিংহ'), ('jamalpur', 'জামালপুর'), ('kishorganj', 'কিশোরগঞ্জ'), ('other', 'অন্যান্য')], max_length=30, null=True, verbose_name='জেলা'),
        ),
        migrations.AlterField(
            model_name='chamberpatient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'পুরুষ'), ('female', 'মহিলা'), ('other', 'অন্যান্য')], max_length=10, null=True, verbose_name='লিঙ্গ'),
        ),
    ]
